import os

class FileManager:
    def __init__(self, base_dir="workspace"):
        self.base_dir = os.path.abspath(base_dir)
        if not os.path.exists(self.base_dir):
            os.makedirs(self.base_dir)

    def _get_safe_path(self, file_name):
        safe_path = os.path.abspath(os.path.join(self.base_dir, file_name))
        if not safe_path.startswith(self.base_dir):
            raise PermissionError("Access denied: Path traversal detected")
        return safe_path

    def write_file(self, file_name, contents):
        path = self._get_safe_path(file_name)
        with open(path, "w", encoding="utf-8") as f:
            f.write(contents)
        return f"CONFIRMED: {file_name} has been written to disk. Length: {len(contents)} chars. You do NOT need to write it again."

    def read_file(self, file_name):
        path = self._get_safe_path(file_name)
        if not os.path.exists(path): return "Error: File not found"
        with open(path, "r") as f: return f.read()

    def save_report(self, task_name, content):
        """Saves a structured Markdown report of the task."""
        filename = f"report_{task_name.replace(' ', '_').lower()}.md"
        path = self._get_safe_path(filename)

        report_template = f"""# Project Overlord: Task Report
                        ## Task: {task_name}

                        {content}

                        ---
                        *Generated by Overlord Autonomous System*
                        """
        with open(path, "w", encoding="utf-8") as f:
            f.write(report_template)
        return f"Report saved to {filename}"

    def list_files(self):
        return os.listdir(self.base_dir)